#############################################################################
# Makefile for building: BubbleKnight
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sat Dec 1 21:14:40 2012
# Project:  BubbleKnight.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile BubbleKnight.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = assassin.cpp \
		bubbleknight.cpp \
		creeper.cpp \
		food.cpp \
		item.cpp \
		main.cpp \
		npc.cpp \
		pin.cpp \
		popper.cpp \
		princess.cpp \
		Protector.cpp \
		scoreboard.cpp \
		shot.cpp \
		speed.cpp \
		stalker.cpp \
		stupidwallgun.cpp \
		user.cpp 
OBJECTS       = assassin.o \
		bubbleknight.o \
		creeper.o \
		food.o \
		item.o \
		main.o \
		npc.o \
		pin.o \
		popper.o \
		princess.o \
		Protector.o \
		scoreboard.o \
		shot.o \
		speed.o \
		stalker.o \
		stupidwallgun.o \
		user.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		BubbleKnight.pro
QMAKE_TARGET  = BubbleKnight
DESTDIR       = 
TARGET        = BubbleKnight

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: BubbleKnight.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile BubbleKnight.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile BubbleKnight.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/BubbleKnight1.0.0 || $(MKDIR) .tmp/BubbleKnight1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/BubbleKnight1.0.0/ && $(COPY_FILE) --parents assassin.h bubbleknight.h creeper.h food.h item.h linkedlist.h node.h npc.h pin.h popper.h princess.h Protector.h scoreboard.h shot.h speed.h stalker.h stupidwallgun.h user.h .tmp/BubbleKnight1.0.0/ && $(COPY_FILE) --parents assassin.cpp bubbleknight.cpp creeper.cpp food.cpp item.cpp main.cpp npc.cpp pin.cpp popper.cpp princess.cpp Protector.cpp scoreboard.cpp shot.cpp speed.cpp stalker.cpp stupidwallgun.cpp user.cpp .tmp/BubbleKnight1.0.0/ && (cd `dirname .tmp/BubbleKnight1.0.0` && $(TAR) BubbleKnight1.0.0.tar BubbleKnight1.0.0 && $(COMPRESS) BubbleKnight1.0.0.tar) && $(MOVE) `dirname .tmp/BubbleKnight1.0.0`/BubbleKnight1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/BubbleKnight1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

assassin.o: assassin.cpp assassin.h \
		stalker.h \
		npc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o assassin.o assassin.cpp

bubbleknight.o: bubbleknight.cpp bubbleknight.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bubbleknight.o bubbleknight.cpp

creeper.o: creeper.cpp creeper.h \
		stalker.h \
		npc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o creeper.o creeper.cpp

food.o: food.cpp food.h \
		item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o food.o food.cpp

item.o: item.cpp item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o item.o item.cpp

main.o: main.cpp Protector.h \
		bubbleknight.h \
		popper.h \
		npc.h \
		item.h \
		linkedlist.h \
		node.h \
		food.h \
		stalker.h \
		pin.h \
		shot.h \
		speed.h \
		princess.h \
		stupidwallgun.h \
		creeper.h \
		assassin.h \
		scoreboard.h \
		user.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

npc.o: npc.cpp npc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o npc.o npc.cpp

pin.o: pin.cpp pin.h \
		item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pin.o pin.cpp

popper.o: popper.cpp popper.h \
		npc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o popper.o popper.cpp

princess.o: princess.cpp princess.h \
		stalker.h \
		npc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o princess.o princess.cpp

Protector.o: Protector.cpp Protector.h \
		bubbleknight.h \
		popper.h \
		npc.h \
		item.h \
		linkedlist.h \
		node.h \
		food.h \
		stalker.h \
		pin.h \
		shot.h \
		speed.h \
		princess.h \
		stupidwallgun.h \
		creeper.h \
		assassin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Protector.o Protector.cpp

scoreboard.o: scoreboard.cpp scoreboard.h \
		user.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scoreboard.o scoreboard.cpp

shot.o: shot.cpp shot.h \
		npc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shot.o shot.cpp

speed.o: speed.cpp speed.h \
		item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o speed.o speed.cpp

stalker.o: stalker.cpp stalker.h \
		npc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stalker.o stalker.cpp

stupidwallgun.o: stupidwallgun.cpp stupidwallgun.h \
		stalker.h \
		npc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stupidwallgun.o stupidwallgun.cpp

user.o: user.cpp user.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o user.o user.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

